#!/usr/bin/python3

"""
Run a command, capturing stdout and stderr to a log file, create a
status file which can easily be checked for by icinga.
"""

import datetime
import os
import sys
import subprocess
import threading

def write_output(fh, label):
    for line in fh:
        logfh.write(
                bytes(
                    label + " " +
                    datetime.datetime.today().isoformat() + " ",
                    encoding="utf-8"
                ) +
                line
              )
        output_seen[label] = True

def touch(path):
    try:
        os.utime(path)
    except:
        with open(path, "wb") as f:
            pass

def remove(path):
    try:
        os.remove(path)
    except:
        pass

basename = os.path.basename(sys.argv[1])
logdir = os.path.join(os.environ["HOME"], "log", "cronwrapper", basename)
os.makedirs(logdir, exist_ok=True)

logfile = os.path.join(logdir, datetime.datetime.today().isoformat() + ".log")
output_seen = {}

with open(logfile, mode='wb', buffering=0) as logfh:

    with subprocess.Popen(sys.argv[1:],
                          stdin=subprocess.DEVNULL,
                          stdout=subprocess.PIPE,
                          stderr=subprocess.PIPE
         ) as p:
        to = threading.Thread(target=write_output, args=(p.stdout, 'out'))
        to.start()
        te = threading.Thread(target=write_output, args=(p.stderr, 'err'))
        te.start()
        rc = p.wait()
        to.join()
        te.join()
        logfh.write(
                bytes(
                    "ctl" + " " +
                    datetime.datetime.today().isoformat() + " " +
                    "command returned %s" % (rc) + 
                    "\n",
                    encoding="utf-8"
                )
              )
statusfile = os.path.join(logdir, "status")

if rc == 0 and "err" not in output_seen:
    touch(os.path.join(logdir, "ok"))
    remove(os.path.join(logdir, "fail"))
else:
    touch(os.path.join(logdir, "fail"))
    remove(os.path.join(logdir, "ok"))
    touch(os.path.join(logdir, "fail_sticky"))
sys.exit(0)


# vim: tw=79
